version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  click-here-for-errors:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:

            - run: npm install
            - run: npm test

                
                    
workflows:
    click-here-for-errors:
      jobs:
        - click-here-for-errors
